### ISSUE TITLE
balance(ce"Cl2 + IO3{-} = IO4{-}") fails.

### ISSUE THREAD

**Issue by eisthf** [zdroid/ChemEquations.jl#5]
The balanced equation for the skeleton eq. Cl2 + IO3{-} = IO4{-} in alkaline solution is:
IO3 + 2Cl2 + 2OH{-} = IO4{-} + 2Cl{-} + H2O

I tried balance(ce"Cl2 + IO3{-} = IO4{-}"), which fails.

I tried giving all reactants and products like:
balance(ce"Cl2 + IO3{-} + OH{-} = IO4{-} + Cl{-}")
but can't be balanced.

**Comment by zlatanvasovic** [comment]
Due to the current simplicity, equation completion is not supported yet. That means you have to write all reactants out:
```jl
julia> balance(ce"IO3 + Cl2 + OH{-} = IO4{-} + Cl{-} + H2O")
2 IO3 + Cl2 + 4 OH{-} = 2 IO4{-} + 2 Cl{-} + 2 H2O
```

Your second example may be missing `H{+}` for complete ionic reaction:
```jl
julia> balance(ce"Cl2 + IO3{-} + OH{-} = IO4{-} + Cl{-} + H{+}")
Cl2 + IO3{-} + OH{-} = IO4{-} + 2 Cl{-} + H{+}
```

 I plan to support equation completion (like webqc.org does), and if you have some ideas how to do that, we can try that.

**Comment by eisthf** [comment]
Oh I see. I played with it to solve some more redox equations and it worked well. How wonderful algorithm it is! and I am so surprised that redox eq can be balanced without knowledge of oxidation numbers.

**Comment by zlatanvasovic** [comment]
@eisthf Thanks! It's actually something you can do on paper as well (i.e. solve a system of linear equations), but in this package it's automated.
